# Generated by Django 5.1.3 on 2024-11-17 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0002_remove_purchaseproduct_warehouse_purchase_warehouse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="gst",
        ),
    ]
