# Generated by Django 5.1.3 on 2024-11-19 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "management",
            "0004_remove_product_reorder_level_alter_sale_subtotal_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="sales_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
