# Generated by Django 5.1.3 on 2024-11-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0005_sale_sales_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseproductsale",
            name="gst_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
