# Generated by Django 5.1.3 on 2024-11-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0006_purchaseproductsale_gst_percentage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="subtotal",
            new_name="sub_total",
        ),
        migrations.AddField(
            model_name="purchaseproductsale",
            name="sub_selling_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="gst_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saleproduct",
            name="gst_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saleproduct",
            name="sub_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
