# Generated by Django 5.1.3 on 2024-11-19 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0007_rename_subtotal_sale_sub_total_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseproductsale",
            old_name="gst_percentage",
            new_name="gst_percent",
        ),
    ]
